services:
  - type: worker  # Используем 'worker', так как боту не нужен веб-сервер
    name: telegram-sticker-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false  # 'sync: false' означает, что вы введете его в дашборде Render
      - key: PYTHON_VERSION
        value: "3.11.5"